### ingest_daily_support_tickets

In [12]:
import sys
print(sys.executable)

c:\Users\prath\anaconda3\python.exe

In [2]:
! pip install boto3
! pip install python-dotenv
! pip install pymysql      #Mysql driver for python to connect to sql

import os            #For env variables
import pandas as pd     # For analysis
import boto3               #Its a SDK to interact with AWS services using python
from io import StringIO    #  Treat a normal string like a file.                  #
from sqlalchemy import create_engine      #For DB connection
from datetime import datetime, timedelta   #to deal with dates

from dotenv import load_dotenv
load_dotenv("sample.env")         #To load env file



# Example: Pandas read_csv() expects a file.

# But you have CSV data as a string (API response, logs, etc.)

# Without StringIO → Pandas will throw an error.
# With StringIO → Pandas thinks it's reading a real file.

# # df (your data)
# ↓
# convert df to CSV text
# ↓
# store CSV text in memory (StringIO)
# ↓
# upload that CSV text to S3 as an object

# os whenever Python code wants to access environment variables

# PyMySQL → only helps Python talk to MySQL (low-level)
# SQLAlchemy → helps Python work with databases in a clean, powerful way (high-level)

Requirement already satisfied: boto3 in c:\users\prath\anaconda3\lib\site-packages (1.43.29)
Requirement already satisfied: botocore<1.44.0,>=1.43.29 in c:\users\prath\anaconda3\lib\site-packages (from boto3) (1.43.29)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\prath\anaconda3\lib\site-packages (from boto3) (1.0.1)
Requirement already satisfied: s3transfer<0.19.0,>=0.18.0 in c:\users\prath\anaconda3\lib\site-packages (from boto3) (0.18.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\prath\anaconda3\lib\site-packages (from botocore<1.44.0,>=1.43.29->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\prath\anaconda3\lib\site-packages (from botocore<1.44.0,>=1.43.29->boto3) (2.5.0)
Requirement already satisfied: six>=1.5 in c:\users\prath\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.29->boto3) (1.17.0)
Requirement already satisfied: python-dotenv in c:\users\prath\anaconda3\lib\site-packages (1.1.0)

ERROR: Invalid requirement: '#Mysql': Expected package name at the start of dependency specifier
    #Mysql
    ^

True

In [3]:
# ---------- DB CONFIG ---------- Can get from DB under schema
db_config = {
    "host": "localhost",
    "port": "3306",
    "user": "root",  # change
    "password": "root", # change
    "database": "careplus_support_db"
}

# S3 configuration(Target bucket name)
S3_BUCKET = "care-plus-project-14062026" 
S3_PREFIX = "support-tickets-db/raw_tickets/"

DATE_TRACKER_FILE = "date_tracker.txt"    # to track last processed date,open() function takes a string file name and opens the file for you.

#AWS config from env(# Access keys become env, when yOU decide to store them as environment variables)

AWS_CONFIG = {
    "aws_access_key_id": os.getenv("AWS_ACCESS_KEY"),  
    "aws_secret_access_key": os.getenv("SECRET_KEY"),
    "region_name": os.getenv("REGION")
}

In [4]:
# ---------- UTILITY FUNCTIONS ----------

# Create db engine
# This is a SQLAlchemy connection URL.
# It tells SQLAlchemy:
# Which database you want to connect to
# Which driver to use
# What credentials to use
# Where the database is located

def get_engine(config):
    return create_engine(f"mysql+pymysql://{config['user']}:{config['password']}@{config['host']}:{config['port']}/{config['database']}")

def upload_to_s3(df, bucket, key):    #df is dataframe(data),target bucket, object 
    csv_buffer = StringIO()            #data is stored in memory not in disk to improve performance     
    df.to_csv(csv_buffer, index=False)  #conveting df to csv

    s3 = boto3.client('s3', **AWS_CONFIG)    #what service to use using config,generally use ** infront of config Take the dictionary named config
                                             #and unpack it into key=value arguments.
    s3.put_object(Bucket=bucket, Key=key, Body=csv_buffer.getvalue())    #uploading
    print(f"✅ Uploaded to s3://{bucket}/{key}")   

def read_last_date(file_path):       #last date 30 jun,read the date of july1st     
    if os.path.exists(file_path):
        with open(file_path, 'r') as f:
            return f.read().strip()
    return "2025-06-30"  # Starting point before 1st July

def update_last_date(file_path, new_date):
    with open(file_path, 'w') as f:
        f.write(new_date)

def get_next_date(last_date_str):
    last_date = datetime.strptime(last_date_str, "%Y-%m-%d")
    next_date = last_date + timedelta(days=1)
    return next_date.strftime("%Y-%m-%d")

# ---------- MAIN INGESTION LOGIC ----------
def run_ingestion():
    engine = get_engine(db_config)
    last_date = read_last_date(DATE_TRACKER_FILE)
    next_date = get_next_date(last_date)

    # Query only that day’s data
    query = f"""
        SELECT * FROM support_tickets
        WHERE DATE(created_at) = '{next_date}';
    """
    df = pd.read_sql(query, engine)
    print(df.shape)
    print(df.head(10))

    if df.empty:
        print(f"⚠️ No data found for {next_date}. Skipping upload.")
        return

    # Upload to S3
    s3_key = f"{S3_PREFIX}support_tickets_{next_date}.csv"
    upload_to_s3(df, S3_BUCKET, s3_key)

    # Update date tracker
    update_last_date(DATE_TRACKER_FILE, next_date)
    print(f"📅 Updated tracker to {next_date}")

# Run
if __name__ == "__main__":
    run_ingestion()


# IMPORT happens when:
# ✔ Airflow loads your file
# ✔ Lambda loads your file
# ✔ Tests import your file
# ✔ Another script imports your file
# ✔ You split code into multiple files
# ✔ You reuse functions from this file

# Without __main__:
#     run_ingestion() runs automatically on import → BAD

# With __main__:
#     run_ingestion() runs ONLY when file is executed directly → GOOD

(23, 10)
    ticket_id        created_at       resolved_at  agent priority  \
0  TCK0710000  2025-07-10 00:04  2025-07-10 02:00  Arjun   Medium
1  TCK0710001  2025-07-10 01:14  2025-07-11 08:40  Arjun   Medium
2  TCK0710002  2025-07-10 01:26  2025-07-11 12:57  Arjun     High
3  TCK0710003  2025-07-10 02:24  2025-07-10 23:53  Kavya      Low
4  TCK0710004  2025-07-10 02:26  2025-07-10 23:39  Arjun    Medum
5  TCK0710005  2025-07-10 02:30  2025-07-10 23:34  Kavya      Hgh
6  TCK0710006  2025-07-10 03:00  2025-07-10 17:39  Arjun   Medium
7  TCK0710007  2025-07-10 03:00  2025-07-10 12:08  Arjun    Medum
8  TCK0710008  2025-07-10 03:14  2025-07-10 11:29  Kavya   Medium
9  TCK0710009  2025-07-10 03:24  2025-07-10 15:52  Kavya      Low

  num_interactions         IssUeCat   channel     status agent_feedback
0                8       Bug Report      Chat   Resolved
1                5  Payment Failure  Web Form  Escalated
2          -999999      Login Issue     Phone   Resolved
3                6  Payment Failure     Email   Resolved
4          -999999   Account Locked     Phone   Resolved
5                2  Payment Failure     Email   Resolved
6          -999999      Login Issue      Chat   Resolved
7                5   Account Locked     Phone   Resolved
8                7      Login Issue     Email   Resolved
9                6       Bug Report     Email   Resolved
✅ Uploaded to s3://care-plus-project-14062026/support-tickets-db/raw_tickets/support_tickets_2025-07-10.csv
📅 Updated tracker to 2025-07-10

In [5]:
# No need to run every time to upload every single data. So we are using looping

def run_ingestion_loop():
    while True:
        last_date = read_last_date(DATE_TRACKER_FILE)
        next_date = get_next_date(last_date)

        print(f"\n📅 Processing Date: {next_date}")

        run_ingestion()

        # Stop when no more data is available
        engine = get_engine(db_config)
        query = f"""
            SELECT * FROM support_tickets
            WHERE DATE(created_at) = '{next_date}';
        """
        df = pd.read_sql(query, engine)

        if df.empty:
            print("🚫 No more data found. Stopping pipeline.")
            break

if __name__ == "__main__":
    run_ingestion_loop()

📅 Processing Date: 2025-07-03
(26, 10)
    ticket_id        created_at       resolved_at   agent priority  \
0  TCK0703000  2025-07-03 00:25  2025-07-03 01:58   Arjun       Lw
1  TCK0703001  2025-07-03 01:00  2025-07-03 16:32   Sneha   Medium
2  TCK0703002  2025-07-03 01:19  2025-07-03 12:26   Sneha       Lw
3  TCK0703003  2025-07-03 03:00              None   Arjun    Medum
4  TCK0703004  2025-07-03 03:14  2025-07-03 16:08   Sneha   Medium
5  TCK0703004  2025-07-03 03:14  2025-07-03 16:08   Sneha   Medium
6  TCK0703005  2025-07-03 03:57  2025-07-03 17:32   Arjun   Medium
7  TCK0703006  2025-07-03 04:39  2025-07-04 07:43  Ananya     High
8  TCK0703007  2025-07-03 05:50  2025-07-03 16:29   Sneha     High
9  TCK0703008  2025-07-03 05:55  2025-07-03 22:53  Ananya       Lw

  num_interactions         IssUeCat   channel    status agent_feedback
0                2  Feature Request      Chat  Resolved
1          -999999  Payment Failure  Web Form  Resolved
2                1  Feature Request     Email  Resolved
3                2  Feature Request  Web Form      Open
4                6      Login Issue      Chat  Resolved
5                6      Login Issue      Chat  Resolved
6                1   Account Locked     Email  Resolved
7                8       Bug Report     Email  Resolved
8                2  Payment Failure     Phone  Resolved
9                2      Login Issue  Web Form  Resolved
✅ Uploaded to s3://care-plus-project-14062026/support-tickets-db/raw_tickets/support_tickets_2025-07-03.csv
📅 Updated tracker to 2025-07-03

📅 Processing Date: 2025-07-04
(27, 10)
    ticket_id        created_at       resolved_at   agent priority  \
0  TCK0704000  2025-07-04 00:15  2025-07-04 18:23   Kavya   Medium
1  TCK0704000  2025-07-04 00:15  2025-07-04 18:23   Kavya   Medium
2  TCK0704001  2025-07-04 00:27  2025-07-04 06:10  Ananya   Medium
3  TCK0704002  2025-07-04 00:30  2025-07-04 07:29   Kavya      Low
4  TCK0704003  2025-07-04 00:35  2025-07-04 06:59   Rohit       Lw
5  TCK0704003  2025-07-04 00:35  2025-07-04 06:59   Rohit       Lw
6  TCK0704004  2025-07-04 01:09  2025-07-04 16:18   Kavya       Lw
7  TCK0704005  2025-07-04 02:37              None   Arjun      Low
8  TCK0704006  2025-07-04 02:39  2025-07-05 07:31   Sneha       Lw
9  TCK0704007  2025-07-04 02:41  2025-07-05 12:39   Kavya   Medium

  num_interactions         IssUeCat channel    status agent_feedback
0                3       Bug Report    Chat  Resolved
1                3       Bug Report    Chat  Resolved
2                8       Bug Report   Email  Resolved
3                1      Login Issue   Email  Resolved
4                3   Account Locked   Email  Resolved
5                3   Account Locked   Email  Resolved
6          -999999  Payment Failure    Chat  Resolved
7                4  Feature Request   Email      Open
8                8  Payment Failure    Chat  Resolved
9                5      Login Issue   Email  Resolved
✅ Uploaded to s3://care-plus-project-14062026/support-tickets-db/raw_tickets/support_tickets_2025-07-04.csv
📅 Updated tracker to 2025-07-04

📅 Processing Date: 2025-07-05
(22, 10)
    ticket_id        created_at       resolved_at   agent priority  \
0  TCK0705000  2025-07-05 01:01  2025-07-05 20:44  Ananya   Medium
1  TCK0705001  2025-07-05 01:31  2025-07-05 23:06   Kavya      Low
2  TCK0705002  2025-07-05 01:53  2025-07-05 17:10   Sneha    Medum
3  TCK0705002  2025-07-05 01:53  2025-07-05 17:10   Sneha    Medum
4  TCK0705003  2025-07-05 03:45  2025-07-06 09:57   Sneha   Medium
5  TCK0705004  2025-07-05 04:24              None   Arjun   Medium
6  TCK0705005  2025-07-05 04:54  2025-07-06 08:36   Arjun     High
7  TCK0705006  2025-07-05 05:13  2025-07-06 00:03   Rohit   Medium
8  TCK0705007  2025-07-05 05:54  2025-07-05 07:31   Rohit      Hgh
9  TCK0705008  2025-07-05 06:06  2025-07-05 21:19  Ananya    Medum

  num_interactions         IssUeCat channel    status agent_feedback
0                6       Bug Report    Chat  Resolved
1                8      Login Issue   Phone  Resolved
2                2  Payment Failure    Chat  Resolved
3                2  Payment Failure    Chat  Resolved
4                6  Feature Request   Phone  Resolved
5                2   Account Locked   Email      Open
6                1   Account Locked   Phone  Resolved
7          -999999   Account Locked   Phone  Resolved
8                4  Payment Failure   Phone  Resolved
9          -999999  Payment Failure    Chat  Resolved
✅ Uploaded to s3://care-plus-project-14062026/support-tickets-db/raw_tickets/support_tickets_2025-07-05.csv
📅 Updated tracker to 2025-07-05

📅 Processing Date: 2025-07-06
(25, 10)
    ticket_id        created_at       resolved_at   agent priority  \
0  TCK0706000  2025-07-06 00:42  2025-07-07 04:12   Kavya      Low
1  TCK0706001  2025-07-06 00:43  2025-07-07 07:35   Rohit   Medium
2  TCK0706002  2025-07-06 00:51  2025-07-07 11:27  Ananya   Medium
3  TCK0706003  2025-07-06 00:57              None   Arjun   Medium
4  TCK0706004  2025-07-06 01:56              None   Rohit   Medium
5  TCK0706005  2025-07-06 02:26  2025-07-06 21:45   Kavya     High
6  TCK0706006  2025-07-06 03:45  2025-07-07 07:33   Arjun    Medum
7  TCK0706007  2025-07-06 04:05              None   Kavya      Hgh
8  TCK0706008  2025-07-06 04:43  2025-07-07 10:44  Ananya     High
9  TCK0706009  2025-07-06 05:06  2025-07-06 23:32  Ananya   Medium

  num_interactions         IssUeCat   channel    status agent_feedback
0                3  Feature Request      Chat  Resolved
1          -999999       Bug Report     Phone  Resolved
2                3   Account Locked     Phone  Resolved
3                1      Login Issue  Web Form      Open
4                5   Account Locked     Phone      Open
5                4   Account Locked     Email  Resolved
6                8  Payment Failure  Web Form  Resolved
7                4   Account Locked     Email      Open
8          -999999   Account Locked     Email  Resolved
9                2   Account Locked     Phone  Resolved
✅ Uploaded to s3://care-plus-project-14062026/support-tickets-db/raw_tickets/support_tickets_2025-07-06.csv
📅 Updated tracker to 2025-07-06

📅 Processing Date: 2025-07-07
(24, 10)
    ticket_id        created_at       resolved_at  agent priority  \
0  TCK0707000  2025-07-07 01:18  2025-07-08 07:16  Rohit    Medum
1  TCK0707001  2025-07-07 01:49              None  Arjun   Medium
2  TCK0707001  2025-07-07 01:49              None  Arjun   Medium
3  TCK0707002  2025-07-07 01:51  2025-07-07 19:43  Sneha       Lw
4  TCK0707003  2025-07-07 02:40  2025-07-08 08:31  Sneha     High
5  TCK0707004  2025-07-07 03:12  2025-07-07 20:55  Sneha     High
6  TCK0707005  2025-07-07 03:30  2025-07-08 05:48  Arjun     High
7  TCK0707006  2025-07-07 03:31  2025-07-07 06:46  Sneha   Medium
8  TCK0707007  2025-07-07 03:47  2025-07-08 08:47  Sneha      Low
9  TCK0707008  2025-07-07 03:58  2025-07-07 12:41  Sneha   Medium

  num_interactions         IssUeCat   channel    status agent_feedback
0                4      Login Issue     Phone  Resolved
1          -999999  Payment Failure     Email      Open
2          -999999  Payment Failure     Email      Open
3                8  Payment Failure     Email  Resolved
4                6   Account Locked  Web Form  Resolved
5                1   Account Locked      Chat  Resolved
6                2  Payment Failure     Phone  Resolved
7                1  Feature Request     Phone  Resolved
8                7   Account Locked     Phone  Resolved
9          -999999  Payment Failure     Email  Resolved
✅ Uploaded to s3://care-plus-project-14062026/support-tickets-db/raw_tickets/support_tickets_2025-07-07.csv
📅 Updated tracker to 2025-07-07

📅 Processing Date: 2025-07-08
(31, 10)
    ticket_id        created_at       resolved_at   agent priority  \
0  TCK0708000  2025-07-08 00:02  2025-07-09 02:30   Rohit      Low
1  TCK0708001  2025-07-08 00:41  2025-07-08 17:24   Kavya     High
2  TCK0708002  2025-07-08 01:13  2025-07-08 10:59   Rohit   Medium
3  TCK0708003  2025-07-08 01:41              None   Arjun   Medium
4  TCK0708004  2025-07-08 02:05  2025-07-08 22:01  Ananya       Lw
5  TCK0708005  2025-07-08 02:54  2025-07-08 15:50   Sneha      Low
6  TCK0708006  2025-07-08 03:20              None   Sneha   Medium
7  TCK0708007  2025-07-08 03:24  2025-07-08 12:47   Rohit    Medum
8  TCK0708008  2025-07-08 03:40  2025-07-08 10:14  Ananya   Medium
9  TCK0708009  2025-07-08 03:42  2025-07-09 08:02   Arjun       Lw

  num_interactions         IssUeCat   channel    status agent_feedback
0                4   Account Locked  Web Form  Resolved
1                8   Account Locked  Web Form  Resolved
2                8   Account Locked     Email  Resolved
3                5  Payment Failure  Web Form      Open
4                5       Bug Report      Chat  Resolved
5                4  Payment Failure  Web Form  Resolved
6                4   Account Locked     Phone      Open
7                4  Feature Request     Phone  Resolved
8          -999999      Login Issue  Web Form  Resolved
9                2  Payment Failure     Email  Resolved
✅ Uploaded to s3://care-plus-project-14062026/support-tickets-db/raw_tickets/support_tickets_2025-07-08.csv
📅 Updated tracker to 2025-07-08

📅 Processing Date: 2025-07-09
(31, 10)
    ticket_id        created_at       resolved_at  agent priority  \
0  TCK0709000  2025-07-09 00:20  2025-07-09 16:30  Arjun      Low
1  TCK0709000  2025-07-09 00:20  2025-07-09 16:30  Arjun      Low
2  TCK0709001  2025-07-09 00:22  2025-07-09 22:49  Rohit       Lw
3  TCK0709002  2025-07-09 00:35  2025-07-09 10:39  Kavya     High
4  TCK0709003  2025-07-09 00:59              None  Kavya   Medium
5  TCK0709004  2025-07-09 01:26  2025-07-09 16:46  Sneha   Medium
6  TCK0709005  2025-07-09 02:00  2025-07-09 18:17  Arjun     High
7  TCK0709006  2025-07-09 02:52  2025-07-09 04:12  Rohit      Low
8  TCK0709007  2025-07-09 03:02  2025-07-09 13:25  Rohit   Medium
9  TCK0709008  2025-07-09 03:10  2025-07-09 05:53  Sneha     High

  num_interactions         IssUeCat   channel    status agent_feedback
0                1   Account Locked     Phone  Resolved
1                1   Account Locked     Phone  Resolved
2                6       Bug Report     Phone  Resolved
3                4  Feature Request     Email  Resolved
4                7       Bug Report     Phone      Open
5          -999999  Payment Failure     Email  Resolved
6          -999999  Feature Request  Web Form  Resolved
7                5      Login Issue  Web Form  Resolved
8          -999999      Login Issue     Phone  Resolved
9                1  Feature Request     Phone  Resolved
✅ Uploaded to s3://care-plus-project-14062026/support-tickets-db/raw_tickets/support_tickets_2025-07-09.csv
📅 Updated tracker to 2025-07-09

📅 Processing Date: 2025-07-10
(23, 10)
    ticket_id        created_at       resolved_at  agent priority  \
0  TCK0710000  2025-07-10 00:04  2025-07-10 02:00  Arjun   Medium
1  TCK0710001  2025-07-10 01:14  2025-07-11 08:40  Arjun   Medium
2  TCK0710002  2025-07-10 01:26  2025-07-11 12:57  Arjun     High
3  TCK0710003  2025-07-10 02:24  2025-07-10 23:53  Kavya      Low
4  TCK0710004  2025-07-10 02:26  2025-07-10 23:39  Arjun    Medum
5  TCK0710005  2025-07-10 02:30  2025-07-10 23:34  Kavya      Hgh
6  TCK0710006  2025-07-10 03:00  2025-07-10 17:39  Arjun   Medium
7  TCK0710007  2025-07-10 03:00  2025-07-10 12:08  Arjun    Medum
8  TCK0710008  2025-07-10 03:14  2025-07-10 11:29  Kavya   Medium
9  TCK0710009  2025-07-10 03:24  2025-07-10 15:52  Kavya      Low

  num_interactions         IssUeCat   channel     status agent_feedback
0                8       Bug Report      Chat   Resolved
1                5  Payment Failure  Web Form  Escalated
2          -999999      Login Issue     Phone   Resolved
3                6  Payment Failure     Email   Resolved
4          -999999   Account Locked     Phone   Resolved
5                2  Payment Failure     Email   Resolved
6          -999999      Login Issue      Chat   Resolved
7                5   Account Locked     Phone   Resolved
8                7      Login Issue     Email   Resolved
9                6       Bug Report     Email   Resolved
✅ Uploaded to s3://care-plus-project-14062026/support-tickets-db/raw_tickets/support_tickets_2025-07-10.csv
📅 Updated tracker to 2025-07-10

📅 Processing Date: 2025-07-11
(23, 10)
    ticket_id        created_at       resolved_at   agent priority  \
0  TCK0711000  2025-07-11 00:01  2025-07-11 06:35  Ananya     High
1  TCK0711001  2025-07-11 00:50  2025-07-11 05:15  Ananya      Low
2  TCK0711002  2025-07-11 00:55  2025-07-12 02:23   Sneha   Medium
3  TCK0711003  2025-07-11 01:17  2025-07-11 22:43   Rohit      Low
4  TCK0711004  2025-07-11 01:24  2025-07-12 08:53  Ananya   Medium
5  TCK0711004  2025-07-11 01:24  2025-07-12 08:53  Ananya   Medium
6  TCK0711005  2025-07-11 03:16  2025-07-11 07:34   Sneha    Medum
7  TCK0711006  2025-07-11 04:06  2025-07-11 19:15   Kavya      Low
8  TCK0711007  2025-07-11 04:26  2025-07-12 07:26   Kavya      Low
9  TCK0711008  2025-07-11 04:44  2025-07-11 08:01  Ananya      Low

  num_interactions         IssUeCat   channel    status agent_feedback
0          -999999  Feature Request     Phone  Resolved
1                1  Feature Request     Phone  Resolved
2          -999999  Feature Request     Email  Resolved
3                2   Account Locked     Email  Resolved
4                4  Feature Request     Email  Resolved
5                4  Feature Request     Email  Resolved
6                5  Feature Request     Email  Resolved
7                7       Bug Report  Web Form  Resolved
8                5       Bug Report     Email  Resolved
9                4   Account Locked     Phone  Resolved
✅ Uploaded to s3://care-plus-project-14062026/support-tickets-db/raw_tickets/support_tickets_2025-07-11.csv
📅 Updated tracker to 2025-07-11

📅 Processing Date: 2025-07-12
(33, 10)
    ticket_id        created_at       resolved_at   agent priority  \
0  TCK0712000  2025-07-12 00:37  2025-07-12 10:10   Sneha      Low
1  TCK0712001  2025-07-12 00:42  2025-07-12 14:00   Rohit   Medium
2  TCK0712002  2025-07-12 00:59  2025-07-13 05:13  Ananya      Hgh
3  TCK0712003  2025-07-12 01:11  2025-07-12 02:52  Ananya    Medum
4  TCK0712004  2025-07-12 01:34  2025-07-12 13:34  Ananya   Medium
5  TCK0712005  2025-07-12 01:38  2025-07-12 04:35  Ananya   Medium
6  TCK0712006  2025-07-12 01:45  2025-07-12 02:18   Rohit     High
7  TCK0712007  2025-07-12 01:46  2025-07-13 11:35   Sneha   Medium
8  TCK0712008  2025-07-12 02:01  2025-07-13 01:16   Sneha       Lw
9  TCK0712009  2025-07-12 02:10  2025-07-13 04:18  Ananya     High

  num_interactions         IssUeCat   channel    status agent_feedback
0                8       Bug Report     Phone  Resolved
1          -999999   Account Locked     Phone  Resolved
2                8       Bug Report     Phone  Resolved
3                4       Bug Report  Web Form  Resolved
4                7  Feature Request  Web Form  Resolved
5          -999999   Account Locked  Web Form  Resolved
6                7   Account Locked  Web Form  Resolved
7          -999999       Bug Report  Web Form  Resolved
8                2      Login Issue     Phone  Resolved
9                5  Feature Request  Web Form  Resolved
✅ Uploaded to s3://care-plus-project-14062026/support-tickets-db/raw_tickets/support_tickets_2025-07-12.csv
📅 Updated tracker to 2025-07-12

📅 Processing Date: 2025-07-13
(28, 10)
    ticket_id        created_at       resolved_at   agent priority  \
0  TCK0713000  2025-07-13 00:06  2025-07-13 21:58   Sneha      Low
1  TCK0713001  2025-07-13 00:23  2025-07-14 11:42  Ananya   Medium
2  TCK0713002  2025-07-13 00:23  2025-07-13 03:38   Kavya   Medium
3  TCK0713002  2025-07-13 00:23  2025-07-13 03:38   Kavya   Medium
4  TCK0713003  2025-07-13 01:03  2025-07-14 05:37   Arjun       Lw
5  TCK0713004  2025-07-13 01:09  2025-07-13 14:07   Rohit     High
6  TCK0713005  2025-07-13 01:15  2025-07-13 11:09   Arjun      Low
7  TCK0713006  2025-07-13 02:09  2025-07-13 08:48   Sneha       Lw
8  TCK0713007  2025-07-13 02:41              None   Kavya      Low
9  TCK0713008  2025-07-13 04:56  2025-07-14 04:11   Sneha   Medium

  num_interactions         IssUeCat   channel    status agent_feedback
0                3  Payment Failure  Web Form  Resolved
1                5  Feature Request      Chat  Resolved
2                7      Login Issue  Web Form  Resolved
3                7      Login Issue  Web Form  Resolved
4          -999999  Payment Failure     Phone  Resolved
5                4  Feature Request  Web Form  Resolved
6          -999999   Account Locked      Chat  Resolved
7          -999999   Account Locked      Chat  Resolved
8                7  Feature Request  Web Form      Open
9                5  Payment Failure     Email  Resolved
✅ Uploaded to s3://care-plus-project-14062026/support-tickets-db/raw_tickets/support_tickets_2025-07-13.csv
📅 Updated tracker to 2025-07-13

📅 Processing Date: 2025-07-14
(28, 10)
    ticket_id        created_at       resolved_at   agent priority  \
0  TCK0714000  2025-07-14 00:59  2025-07-14 20:47   Rohit   Medium
1  TCK0714001  2025-07-14 01:07  2025-07-15 04:49   Kavya    Medum
2  TCK0714002  2025-07-14 01:46              None   Sneha      Low
3  TCK0714003  2025-07-14 02:01  2025-07-14 03:05   Arjun   Medium
4  TCK0714004  2025-07-14 02:14              None   Kavya   Medium
5  TCK0714004  2025-07-14 02:14              None   Kavya   Medium
6  TCK0714005  2025-07-14 02:29  2025-07-14 22:09   Rohit    Medum
7  TCK0714006  2025-07-14 03:57  2025-07-14 23:21  Ananya   Medium
8  TCK0714007  2025-07-14 04:10  2025-07-14 23:51   Arjun   Medium
9  TCK0714008  2025-07-14 04:35              None  Ananya      Low

  num_interactions         IssUeCat   channel    status agent_feedback
0                7       Bug Report     Email  Resolved
1                6       Bug Report  Web Form  Resolved
2                5  Feature Request     Phone      Open
3                5   Account Locked      Chat  Resolved
4                3   Account Locked     Email      Open
5                3   Account Locked     Email      Open
6                8  Feature Request      Chat  Resolved
7                4   Account Locked     Email  Resolved
8                4  Feature Request     Phone  Resolved
9                3   Account Locked     Email      Open
✅ Uploaded to s3://care-plus-project-14062026/support-tickets-db/raw_tickets/support_tickets_2025-07-14.csv
📅 Updated tracker to 2025-07-14

📅 Processing Date: 2025-07-15
(28, 10)
    ticket_id        created_at       resolved_at   agent priority  \
0  TCK0715000  2025-07-15 00:41  2025-07-15 09:52   Arjun    Medum
1  TCK0715001  2025-07-15 01:05  2025-07-15 03:00   Arjun    Medum
2  TCK0715002  2025-07-15 01:38  2025-07-15 11:47  Ananya   Medium
3  TCK0715003  2025-07-15 01:55  2025-07-15 22:17   Rohit   Medium
4  TCK0715004  2025-07-15 02:23  2025-07-16 12:51   Arjun   Medium
5  TCK0715005  2025-07-15 02:23  2025-07-16 11:04  Ananya   Medium
6  TCK0715006  2025-07-15 02:48  2025-07-16 01:10   Sneha     High
7  TCK0715007  2025-07-15 02:57  2025-07-15 14:31   Rohit   Medium
8  TCK0715008  2025-07-15 03:20              None  Ananya   Medium
9  TCK0715008  2025-07-15 03:20              None  Ananya   Medium

  num_interactions         IssUeCat   channel    status agent_feedback
0                4       Bug Report     Email  Resolved
1          -999999       Bug Report  Web Form  Resolved
2                8   Account Locked     Email  Resolved
3                6       Bug Report  Web Form  Resolved
4          -999999   Account Locked  Web Form  Resolved
5                1  Feature Request     Phone  Resolved
6                1       Bug Report      Chat  Resolved
7                2  Payment Failure  Web Form  Resolved
8                4   Account Locked      Chat      Open
9                4   Account Locked      Chat      Open

In [1]:
df.info()

NameError: name 'df' is not defined

In [1]:
#Processed Ticket parquet file

import pandas as pd

df=pd.read_parquet("C:/Users/prath/Downloads/run-1781683450387-part-block-0-r-00000-snappy.parquet")
df.head(135)

,ticket_id,created_at,resolved_at,agent,priority_cleaned,num_interactions,Issue_Category,channel,status
0,TCK0701000,2025-07-01 00:13:00,NaT,Sneha,Medium,7,Payment Failure,Chat,Open
1,TCK0701001,2025-07-01 01:24:00,2025-07-01 02:47:00,Kavya,Medium,8,Account Locked,Web Form,Resolved
2,TCK0701002,2025-07-01 01:49:00,2025-07-01 19:25:00,Rohit,Low,3,Bug Report,Web Form,Resolved
3,TCK0701004,2025-07-01 03:03:00,2025-07-02 11:00:00,Ananya,High,5,Bug Report,Chat,Resolved
4,TCK0701005,2025-07-01 03:07:00,2025-07-02 00:35:00,Arjun,High,1,Bug Report,Email,Resolved
...,...,...,...,...,...,...,...,...,...
130,TCK0706019,2025-07-06 09:21:00,2025-07-07 17:31:00,Sneha,Medium,5,Account Locked,Web Form,Resolved
131,TCK0706020,2025-07-06 10:08:00,2025-07-07 00:49:00,Arjun,Medium,6,Login Issue,Phone,Resolved
132,TCK0706020,2025-07-06 10:08:00,2025-07-07 00:49:00,Arjun,Medium,6,Login Issue,Phone,Resolved
133,TCK0706021,2025-07-06 10:18:00,2025-07-07 13:20:00,Rohit,Medium,5,Payment Failure,Email,Resolved
134,TCK0706022,2025-07-06 11:30:00,2025-07-07 18:58:00,Kavya,Low,6,Feature Request,Email,Resolved

In [ ]:

#Curated logs

import pandas as pd

df=pd.read_parquet("C:/Users/prath/Downloads/support_logs_2025-07-07_curated.parquet")
df

   total_logs  error_count  warning_count  avg_cpu_usage  avg_response_time
0          62            4              0              0         985.693548

In [6]:
#Curated Tickets

import pandas as pd

df=pd.read_parquet("C:/Users/prath/Downloads/part-00035-651fef90-058f-460a-88ee-746023bf10c4-c000.snappy.parquet")
df

,total_tickets,resolved_tickets,open_tickets,high_priority,medium_priority,low_priority,avg_interactions,avg_resolution_hours,chat_tickets,email_tickets,phone_tickets,webform_tickets,payment_failure,account_locked,bug_report,login_issue
0,223,180,35,0,0,0,4.430493,17.202216,57,67,56,43,55,47,45,38